language: go

go:
- 1.6.3
- 1.7

go_import_path: dd-logstats

env:
- GLIDE_VERSION=v0.12.3

install:
- mkdir -p $HOME/bin
- export PATH="$HOME/bin:$PATH"
- wget -O- "https://github.com/Masterminds/glide/releases/download/${GLIDE_VERSION}/glide-${GLIDE_VERSION}-linux-amd64.tar.gz" | tar -vxz -C $HOME/bin --strip=1

script:
- make
- make test
